### Site Settings ###
title               : Hugo Le Moine
description         : I'm an apprentice Data Scientist at Airbus and soon to graduate from UTC. I share projects and blog posts related to Python, Data Science and Machine Learning.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : hugolmn/hugolmn.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
#remote_theme        : hugolmn/portfolYOU
links               :
  - "/projects : Projects"
  - "/blog : Blog"
  - "/about-me : About Me"
  - "/assets/resume/CV_EN_Hugo_Le_Moine_EEO.pdf : Resume"

### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/**

### Author Info ###
author:
  name              : Hugo Le Moine
  image             : https://avatars0.githubusercontent.com/u/39267118?s=460&u=88a79cceeb098ab94451086064f0bcd737eaba34&v=4
# behance           : your_username
# dribbble          : your_username
  email             : hugo.le-moine@outlook.fr
#  facebook          : your_username
  github            : hugolmn
# gitlab            : your_username
  instagram         : hugo_le_moine
#  kaggle            : hugolmn
  linkedin          : hugo-le-moine
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 13765085/hugolmn?tab=profile
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
#permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus: hugolmn
### Google analytics ###
analytics: UA-169857487-2

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments
      sitemap: false
  - scope:
      path: "assets/graphs/**"
    values:
      sitemap: false

author-details: true



### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
